In [2]:
import esm
from esm.sdk.api import ESM3InferenceClient

MODEL = "esm3-large-2024-03"
MY_TOKEN = 'uio5AXjvu5Pu3BLNU5EkA'

In [3]:
model: ESM3InferenceClient = esm.sdk.client(MODEL, token=MY_TOKEN)

In [4]:
from esm.sdk.api import (
    ESMProtein,
    LogitsConfig,
)
from esm.utils.structure.protein_chain import ProteinChain

protein = ProteinChain.from_rcsb("1utn")
protein = ESMProtein.from_protein_chain(protein)
protein.coordinates = None

In [5]:
protein

ESMProtein(sequence='IVGGYTCGANTVPYQVSLNSGYHFCGGSLINSQWVVSAAHCYKSGIQVRLGEDNINVVEGNEQFISASKSIVHPSYNSNTLNNDIMLIKLKSAASLNSRVASISLPTSCASAGTQCLISGWGNTKSSGTSYPDVLKCLKAPILSDSSCKSAYPGQITSNMFCAGYLEGGKDSCQGDSGGPVVCSGKLQGIVSWGSGCAQKNKPGVYTKVCNYVSWIKQTIASN', secondary_structure=None, sasa=None, function_annotations=None, coordinates=None, plddt=None, ptm=None, potential_sequence_of_concern=False)

In [6]:
protein_tensor = model.encode(protein)

In [7]:
protein_tensor

ESMProteinTensor(sequence=tensor([ 0, 12,  7,  6,  6, 19, 11, 23,  6,  5, 17, 11,  7, 14, 19, 16,  7,  8,
         4, 17,  8,  6, 19, 21, 18, 23,  6,  6,  8,  4, 12, 17,  8, 16, 22,  7,
         7,  8,  5,  5, 21, 23, 19, 15,  8,  6, 12, 16,  7, 10,  4,  6,  9, 13,
        17, 12, 17,  7,  7,  9,  6, 17,  9, 16, 18, 12,  8,  5,  8, 15,  8, 12,
         7, 21, 14,  8, 19, 17,  8, 17, 11,  4, 17, 17, 13, 12, 20,  4, 12, 15,
         4, 15,  8,  5,  5,  8,  4, 17,  8, 10,  7,  5,  8, 12,  8,  4, 14, 11,
         8, 23,  5,  8,  5,  6, 11, 16, 23,  4, 12,  8,  6, 22,  6, 17, 11, 15,
         8,  8,  6, 11,  8, 19, 14, 13,  7,  4, 15, 23,  4, 15,  5, 14, 12,  4,
         8, 13,  8,  8, 23, 15,  8,  5, 19, 14,  6, 16, 12, 11,  8, 17, 20, 18,
        23,  5,  6, 19,  4,  9,  6,  6, 15, 13,  8, 23, 16,  6, 13,  8,  6,  6,
        14,  7,  7, 23,  8,  6, 15,  4, 16,  6, 12,  7,  8, 22,  6,  8,  6, 23,
         5, 16, 15, 17, 15, 14,  6,  7, 19, 11, 15,  7, 23, 17, 19,  7,  8, 22,
        12, 15

In [8]:
logits_output = model.logits(
    protein_tensor, LogitsConfig(sequence=True, return_embeddings=True)
)

/home/ubuntu/esm/esm/utils/misc.py:273: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(x)


In [9]:
logits_output

LogitsOutput(logits=ForwardTrackData(sequence=tensor([[-25.0000, -25.0000, -24.7500,  ..., -24.8750, -24.6250, -24.8750],
        [-22.1250, -22.2500, -22.1250,  ..., -22.0000, -21.7500, -22.6250],
        [-23.2500, -23.5000, -23.1250,  ..., -23.0000, -23.1250, -23.2500],
        ...,
        [-23.7500, -24.0000, -24.2500,  ..., -24.0000, -23.7500, -24.0000],
        [-21.6250, -21.5000, -21.3750,  ..., -21.2500, -21.1250, -21.6250],
        [-23.5000, -23.2500, -23.2500,  ..., -23.2500, -23.1250, -23.3750]]), structure=None, secondary_structure=None, sasa=None, function=None), embeddings=tensor([[[-0.5391, -0.5117, -0.7656,  ..., -0.4258,  0.3223,  0.1445],
         [-0.1572, -0.1206, -0.5391,  ...,  0.2441,  0.6250,  0.1396],
         [-0.3418, -0.8672, -0.5430,  ..., -0.7109,  0.5195,  0.8672],
         ...,
         [-0.2139,  0.0593, -0.8555,  ...,  0.2275,  0.5859,  0.2197],
         [ 0.0859, -0.6602,  0.7578,  ...,  0.2070,  0.0138, -0.3125],
         [ 0.0058,  0.3359, -0.261

In [10]:
logits_output.embeddings

tensor([[[-0.5391, -0.5117, -0.7656,  ..., -0.4258,  0.3223,  0.1445],
         [-0.1572, -0.1206, -0.5391,  ...,  0.2441,  0.6250,  0.1396],
         [-0.3418, -0.8672, -0.5430,  ..., -0.7109,  0.5195,  0.8672],
         ...,
         [-0.2139,  0.0593, -0.8555,  ...,  0.2275,  0.5859,  0.2197],
         [ 0.0859, -0.6602,  0.7578,  ...,  0.2070,  0.0138, -0.3125],
         [ 0.0058,  0.3359, -0.2617,  ...,  0.5195, -0.1416, -0.7539]]],
       dtype=torch.bfloat16)

In [11]:
logits_output.embeddings.shape

torch.Size([1, 225, 6144])

In [12]:
logits_output.embeddings

tensor([[[-0.5391, -0.5117, -0.7656,  ..., -0.4258,  0.3223,  0.1445],
         [-0.1572, -0.1206, -0.5391,  ...,  0.2441,  0.6250,  0.1396],
         [-0.3418, -0.8672, -0.5430,  ..., -0.7109,  0.5195,  0.8672],
         ...,
         [-0.2139,  0.0593, -0.8555,  ...,  0.2275,  0.5859,  0.2197],
         [ 0.0859, -0.6602,  0.7578,  ...,  0.2070,  0.0138, -0.3125],
         [ 0.0058,  0.3359, -0.2617,  ...,  0.5195, -0.1416, -0.7539]]],
       dtype=torch.bfloat16)

In [16]:
emb = logits_output.embeddings.mean(dim=1)

In [17]:
emb

tensor([[-0.0231, -0.0352, -0.3828,  ...,  0.1162,  0.2158,  0.1436]],
       dtype=torch.bfloat16)

In [18]:
emb.shape

torch.Size([1, 6144])

In [5]:
import lmdb
import json
import pandas as pd
import numpy as np
from pathlib import Path


dfs_lmdb = {}
for data_type in ['train', 'valid', 'test']:
    env = lmdb.open(f'HumanPPI/normal/{data_type}/')
    res = []

    with env.begin() as txn:
        for key, value in txn.cursor():
            if key == b'info' or key == b'length':
                continue
            res.append(json.loads(value))
    
    env.close()

    dfs_lmdb[data_type] = pd.DataFrame(res)

df_lmdb = pd.concat(dfs_lmdb.values())

sequences = list(set(df_lmdb.seq_1) | set(df_lmdb.seq_2))
len(sequences)

5526

In [6]:
import time
import random

import pandas as pd
from esm.sdk import client
from pathlib import Path
from esm.sdk.api import (
    ESMProtein,
    LogitsConfig,
)
from esm.sdk import batch_executor


MY_TOKEN = 'uio5AXjvu5Pu3BLNU5EkA'

# model_name = "esm3-large-2024-03"
# model_name = "esmc-6b-2024-12"
model_name = "esm3-medium-2024-08"

model_name_for_file = model_name.replace('/', '-').replace(' ', '-').replace('_', '-')
f = Path(f'embeddings_{model_name_for_file}.parquet')

if f.exists():
    df_existing = pd.read_parquet(f)
    done_sequences = set(df_existing['sequence'])
else:
    df_existing = pd.DataFrame(columns=['sequence', 'embedding'])
    done_sequences = set()


def calculate_embedding(model, sequence):
    protein = ESMProtein(sequence=sequence)
    protein_tensor = model.encode(protein)
    logits_output = model.logits(
        protein_tensor, LogitsConfig(sequence=True, return_embeddings=True)
    )
    emb = logits_output.embeddings.mean(dim=1)
    return emb[0].tolist()


model = client(model_name, token=MY_TOKEN)

from torch.utils.data import DataLoader
dataloader = DataLoader(
    [s for s in sequences if s not in done_sequences],
    batch_size=40
)

for batch_sequences in dataloader:
    batch_sequences = list(set([seq for seq in batch_sequences if seq not in done_sequences]))
    if len(batch_sequences) == 0:
        continue

    print(f'calculating embeddings for {len(batch_sequences)} sequences...')
    with batch_executor(max_attempts=40) as executor:
        batch_embeddings = executor.execute_batch(user_func=calculate_embedding, model=model, sequence=batch_sequences)

    new_rows = pd.DataFrame({"sequence": batch_sequences, "embedding": batch_embeddings})

    df_existing = pd.concat([df_existing, new_rows], ignore_index=True)
    df_existing.to_parquet(f, index=False)

    for seq in batch_sequences:
        done_sequences.add(seq)

    t = 10 * (random.random() + 1)
    print(f'sleeping {t} seconds...')
    time.sleep(t)


calculating embeddings for 40 sequences...


Processing    0%|                        | 0/40 [Elapsed: 00:02 | Remaining: ?] , Success=0 Fail=0 Retry=0/home/ubuntu/esm/esm/utils/misc.py:273: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(x)
Processing  100%|████████████████████████| 40/40 [Elapsed: 00:06 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 19.597782608333084 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:08 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 14.787377812336079 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:09 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 12.906752541091144 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:08 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 17.102624437871466 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:08 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 16.483224820357837 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:09 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 16.246223422650935 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:09 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 17.418074950214706 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:09 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 17.058189201626725 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:08 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 10.017474764140413 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:07 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 19.593506625256598 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:07 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 10.733458331477443 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:10 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 10.752153133826441 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:10 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 12.196258464951462 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:06 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 11.18905132255457 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:07 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 18.022970180607338 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:07 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 17.5879031424722 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:05 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 14.076681138959904 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:06 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 11.445617395783227 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:06 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 10.915968981929005 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:06 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 14.915583462919244 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:06 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 12.809423090735754 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:06 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 14.837703640264097 seconds...
calculating embeddings for 40 sequences...


Processing  100%|████████████████████████| 40/40 [Elapsed: 00:06 | Remaining: 00:00] , Success=40 Fail=0 Retry=0


sleeping 19.54251494188343 seconds...
calculating embeddings for 6 sequences...


Processing  100%|████████████████████████| 6/6 [Elapsed: 00:03 | Remaining: 00:00] , Success=6 Fail=0 Retry=0


sleeping 14.343992562669685 seconds...


In [7]:
df = pd.read_parquet(f)
df

,sequence,embedding
0,MAAGQNGHEEWVGSAYLFVESSLDKVVLSDAYAHPQQKVAVYRALQ...,"[0.0625, -0.03125, 0.035888671875, -0.05249023..."
1,MALRVTRNSKINAENKAKINMAGAKRVPTAPAATSKPGLRPRTALG...,"[0.205078125, -0.026123046875, 0.0927734375, -..."
2,MSKLSFRARALDASKPLPVFRCEDLPDLHEYASINRAVPQMPTGME...,"[-0.040771484375, -0.07568359375, -0.026611328..."
3,MALPFQKELEKYKNIDEDELLGKLSEEELKQLENVLDDLDPESAML...,"[0.171875, 0.1396484375, -0.095703125, -0.1435..."
4,MKKSIGILSPGVALGMAGSAMSSKFFLVALAIFFSFAQVVIEANSW...,"[0.2109375, -0.0439453125, -0.040283203125, -0..."
...,...,...
5521,MDKQNSQMNASHPETNLPVGYPPQYPPTAFQGPPGYSGYPGPQVSY...,"[-0.06689453125, -0.150390625, 0.1689453125, -..."
5522,MTARGTPSRFLASVLHNGLGRYVQQLQRLSFSVSRDGASSRGAREF...,"[0.1416015625, 0.0419921875, -0.09326171875, -..."
5523,MVGRRALIVLAHSERTSFNYAMKEAAAAALKKKGWEVVESDLYAMN...,"[0.053955078125, 0.0174560546875, -0.083007812..."
5524,MTSHYVIAIFALMSSCLATAGPEPGALCELSPVSASHPVQALMESF...,"[-0.07080078125, -0.0908203125, 0.07373046875,..."


In [16]:
len(set(df.sequence))

3509